version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
      day: "sunday"
    labels:
      - "module:infrastructure"
      - "scope:security"
      - "pr:no-release-notes"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      github-actions:
        patterns:
          - "*"
